### ISSUE TITLE
code simplification suggestion: rolling_hash2_run_until_base

### ISSUE THREAD

**Issue by zhiyuan-zhu** [intel/isa-l_crypto#42]
file: https://github.com/intel/isa-l_crypto/blob/master/rolling_hash/rolling_hash2.c
function: rolling_hash2_run_until_base

I think the following code
<pre><code>
if (trigger == 0) {
	for (; i < max_idx; i++) {
		h = (h << 1) | (h >> (64 - 1));
		h ^= t1[b1[i]] ^ t2[b2[i]];
		if ((h & mask) == 0) {
			*idx = i;
			return h;
		}
	}
} else {
	for (; i < max_idx; i++) {
		h = (h << 1) | (h >> (64 - 1));
		h ^= t1[b1[i]] ^ t2[b2[i]];
		if ((h & mask) == trigger) {
			*idx = i;
			return h;
		}
	}
}
</pre></code>

can be simplified to
<pre><code>
for (; i < max_idx; i++) {
	h = (h << 1) | (h >> (64 - 1));
	h ^= t1[b1[i]] ^ t2[b2[i]];
	if ((h & mask) == trigger) {
		*idx = i;
		return h;
	}
}
</pre></code>

But I ’m not sure if there is something I didn’t think about, would you please help to check whether can I file a patch to modify this? thanks.

**Comment by gbtucker** [comment]
@zhiyuan-zhu this is actually a code optimization.  For this rolling hash function, it is a common usage that the trigger is 0 but not always.  The main loop is quite small, only about a dozen instructions.  In the loop where the trigger is zero it saves 1 or 2 instructions which can be a significant performance improvement in such a tight loop.  I think it is worth it to keep this optimization and not too much of a burden in maintenance since it is easy to read that otherwise the loops are the same.

**Comment by zhiyuan-zhu** [comment]
@gbtucker Thanks a lot, do you mean: if the trigger is zero, it will save the instruction: cmp tmp, trigger ?

And I want to use assembly and loop unrolling to optimize this code, do I also need to implement two cases where the trigger is 0 and non-zero?

**Comment by gbtucker** [comment]
I think you will find it depends and you should experiment to see how it helps.

**Comment by zhiyuan-zhu** [comment]
Got it, thanks a lot.  
I will close this issue.
@gbtucker
